name: test purpose
on:
  pull_request:
    branches:
      - main
      - sub
      - test
  workflow_dispatch:
  push:
jobs:
  lint:
    runs-on: ubontu-latest
    timeout-minutes: 5
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/caches@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest  
    timeout-minutes: 10
    steps:

      - name: Get code
        uses: actions/checkout@v3

      